### ISSUE TITLE
PM can create and submit Project Approval Form (PAF)

### ISSUE THREAD

**Issue by ei8fdb** [OpenTechFund/apply-app#3]
## Additional context
This is a sub-issue of the meta #2 

## User story

> As a programme manager, I want to create a Project Approval Form so that the project can receive their contract

### Demo
This video shows an overview of the design and then walks through the clickable prototype

https://user-images.githubusercontent.com/1899506/155727932-023ec8e0-1bb6-410d-8cb9-a7566ced66ff.mp4

#### Summary
![](https://share.balsamiq.com/c/bbbuZ8L2RXE2fVrYomy2xW.png)

#### 3.0
![](https://share.balsamiq.com/c/2TSv9HEUvxRffPwrQ5A1NB.png)

The user begins with a PAF containing the information Hypha can autopopulate about the project.

#### 3.1 
![](https://share.balsamiq.com/c/2Ziia5umBD4VkG8U5vEQu5.png)

The user needs to complete the "justification and narrative" and "congressional mandate" text fields.

#### 3.2
![](https://share.balsamiq.com/c/6bVmkeaPFAUBKd3T3s61bb.png)

Then they choose which kind of contract the contractor will get - right now we are supporting Fixed Price contracts.

#### 3.4
![](https://share.balsamiq.com/c/kodwFivTXZDYCo4dm1kAAG.png)

They then need to choose which optional contract clause language needs to be added to the contract

#### 3.5
![](https://share.balsamiq.com/c/2c7pF17vm4XQWbTBJ8Vnmn.png)

They then need to click Yes for the "Appropriate costs" questions

#### 3.6
![](https://share.balsamiq.com/c/5BeHKd2Ea4pwU4HpHFEtQq.png)

If the user wants to add the deliverables to the PAF they can. This is optional.

#### 3.7
![](https://share.balsamiq.com/c/oEwTuVy7VmV5rQk7mLy3mf.png)

When the user submits the PAF,  they're brought back to the Project setup page with the Actions to take button "Submit  for approval" disabled as it's been submitted.

If they wanted to edit the PAF, they can click edit.
If they wanted to view the PAF, they can click view.

#### 3.8
![](https://share.balsamiq.com/c/bStNr1UWNGkC3WUnnG7AEb.png)

If the user choose save PAF as draft, they're brought back to the Project setup page with the Actions to take button "Submit  for approval still enabled"  

If they wanted to edit the PAF, they can click edit.
If they wanted to view the PAF, they can click view.

---
## To-Do
- [x] @OpenTechFund/design to add designs to issue
- [x] @OpenTechFund/devs to review designs for implementation
- [x] Di to help organise testing/feedback session with OTF users
- [x] @OpenTechFund/design do testing/feedback session with OTF users
- [x] OTF to sign-off
- [x] @OpenTechFund/design to make sure most up to date designs designs are attached to issue

**Comment by fourthletter** [comment]
- [ ] The action to 'create' an approval form in not in the 'actions to take' section. 

![The action to 'create' an approval form in not in the 'actions to take' section](https://user-images.githubusercontent.com/20019656/150985285-ad97945c-6587-422e-a80c-1dc9e8dc9f21.png)

**Comment by fourthletter** [comment]
QA

_The user begins to fill in a new PAF_
- [ ] NEW PAF is autopopulated with information about the project from Hypha. This include information from the Contractor Setup Form and Proposal. **Do we need to setup several upload buttons for the budget, CV, etc. in the proposal form, or will ALL documents be autopopulated?**

- [ ] Autopopulated Fields
Contractor/Vendor name 
**Reviewer Names & Date Stamp** -- this is currently missing from the design
Proposed Amount
Start & End Date

- [ ] Optional Fields
choose which optional contract clause language needs to be added to the contract
add the deliverables to a text box
- [ ] Required Fields
 (9) "justification and narrative", (10) "congressional mandate" as well as select (11) which kind of contract the contractor will get, click Yes for the "Appropriate costs" questions

_Project setup page_
- [ ] When the user submits the PAF, they're brought back to the Project setup page with the Actions to take button "Submit for approval" disabled as it's been submitted.
- [ ] If they wanted to edit the PAF, they can click edit.
- [ ] If they wanted to view the PAF, they can click view.
- [ ] If the user choose save PAF as draft, they're brought back to the Project setup page with the Actions to take button "Submit for approval still enabled"
- [ ] If they wanted to edit the PAF, they can click edit.
- [ ] If they wanted to view the PAF, they can click view.

**Comment by frjo** [comment]
All the yellow marked parts that is not necessary for staff ability to fill in the form should be removed. Less clutter.

**Comment by ei8fdb** [comment]
@fourthletter 

> Are questions 12 - 13 radio buttons or check boxes?

They are radio buttons, the user can select Yes **or** no, not both.

> Question 2 'this project is part of [insert Fund or Lab]' has an elegant design -- where will this information come from?

This actually isn't needed anymore as the FundName, etc will be in the project review admin bar at the top. (I've changed the design already.) 

> We need Reviewer Names and the Date Stamp on the PAF pdf

This was removed *from this view* based on earlier feedback. It is available in the PAF output which is reviewed. 

> Proposed Amount
> Start & End Date
> budget upload
> cv/resume upload
> other document upload

Why are these needed? They're already added by Hypha automatically.

> Notifications or alert for Contracting role

We don't seem yet to have an issue for compliance and contracting notifications. Can you open one Di and give some detail of what notifications are needed when? Something similar to https://github.com/HyphaApp/hypha/issues/2704 would be helpful.

> In regards to Question 11 the drop-down menu for contract types, e.g., Time & Materials Contract - what is the expected behavior after this selection?

It will operate as a normal dropdown box - the use selects the type of contract and it is selected. Right now the only option that can be selected will be Fied Price.

> choose which optional contract clause language needs to be added to the contract
add the deliverables to a text box, reporting requirement, work permit, open source, security audit


> All the yellow marked parts that is not necessary for staff ability to fill in the form should be removed. Less clutter.

OTF have already reviewed the designs

**Comment by fourthletter** [comment]
@ei8fdb thank you for the above clarifications. I will create a new notification/comm GH issue.

> Proposed Amount
> Start & End Date
> budget upload
> cv/resume upload
> other document upload
> Why are these needed? They're already added by Hypha automatically.

The above items are included on my QA checklist to ensure they appear on the form after development.

**Comment by frjo** [comment]
@fourthletter The first question is if the budget and CV always will come from the submission?

**Comment by fourthletter** [comment]
On May 4 OTF and SimSec met and decided agreed to the current PAF workflow. OTF needs to provide SimSec with the most current version of the PAF.

**Comment by fourthletter** [comment]
On June 10 BT recorded new contracting workflow based on OTF feedback https://saneux.ei8fdb.org/s/moMwk8JgfoCEKDN

**Comment by frjo** [comment]
@fourthletter Do you think we will ever integrate the paf/contracting with IntAcct or any other services?

I suspect no.

If so I start thinking that bringing back the stream field version of the PAF would be the best solution. We already have all the code for that here https://github.com/HyphaApp/hypha/pull/2635/files

Then each organisation can add any fileds they need to the PF and you can have different PAFs for different funds/labs if you so wish.

What do you think?

**Comment by fourthletter** [comment]
@frjo I like this idea as well. Could we try it out? 

I could "design" or put together a form in WagTail to replicate OTF's proposed layout to see if there are any missing fields.

**Comment by frjo** [comment]
See https://github.com/HyphaApp/hypha/issues/2904
