### ISSUE TITLE
Compliance Attorney can review Project Approval Form

### ISSUE THREAD

**Issue by ei8fdb** [OpenTechFund/apply-app#4]
## Additional context
This is a sub-issue of the meta #2 

### Sub-issues
- Compliance attorney carries out required checks

## User story

> As a Compliance attorney, I want to review a Project Approval Form so that I can then create the necessary contract.

---
## To-Do
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [ ] Di to help organise testing/feedback session with OTF users
- [ ] @OpenTechFund/design do testing/feedback session with OTF users
- [x] OTF sign-off design
- [ ] @OpenTechFund/design to make sure most up to date designs designs are attached to issue

**Comment by fourthletter** [comment]
- [ ] OTF may use an external service for SAM & OFAC checks in the near future; this means all Attorney needs to "check" the boxes for compliance reasons.
