### ISSUE TITLE
PM can request changes to Project Approval Form

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#58]
## Additional context
[This is a sub-issue of the meta https://github.com/HyphaApp/hypha/issues/2622](https://github.com/OpenTechFund/apply-app/issues/2)

## User story

> As staff or PM or Lead, I want to request changes to a submitted Project Approval Form so that I can edit and resubmit the correct information.

---

## To-Do
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [ ] Di to help organise testing/feedback session with OTF users
- [ ] do testing/feedback session with OTF users
- [ ] OTF to sign-off
- [ ] @OpenTechFund/design make sure final designs are attached to issue

**Comment by ei8fdb** [comment]
> PAF can be deleted

I'm guessing the PAF still needs to be visible somewhere in Hypha?

> There is an activity when a PAF is edited and/or deleted

Can you give more detail of what activity you want to see?

**Comment by fourthletter** [comment]
Closing this issue because it is 1) duplicative of another design aspect relating to CA approvals and 2) need additional user research, discovery, and testing with program managers.
