### ISSUE TITLE
GC, CFO, CEO can approve the Project Approval Form

### ISSUE THREAD

**Issue by ei8fdb** [OpenTechFund/apply-app#6]
(This issue is a work-in-progress, so I'm locking it until I've finished documenting it fully. If you want to edit it, let me know.) 

## Additional context
This is a sub-issue of the meta #2 

At the moment, we think the process for the GC, CFO, CEO approval will be the same. For now, the same ticket will be used for these 3 users. Collectively I will refer to them as "PAF Approver".

## User story

> As PAF approver, I want to approve the Project Approval Form so that the Compliance Attorney can create the contract for this project.

---
## To-Do
- [x] @OpenTechFund/design to add designs to issue
- [x] @OpenTechFund/devs to review designs for implementation
- [ ] Di to help organise testing/feedback session with OTF users
- [ ] @OpenTechFund/design do testing/feedback session with OTF users
- [ ] OTF to sign-off UI for how users approve PAF
- [ ] OTF to sign-off information displayed and its order
- [ ] @OpenTechFund/design make sure final designs are attached to issue

**Comment by fourthletter** [comment]
- [ ] Fredrik created a new [Contracting user role](https://github.com/HyphaApp/hypha/issues/2557), Approver role already exists in Hypha

**Comment by fourthletter** [comment]
Design Review - 1 March 2022

BT presented #6 Approvers request changes to PAF

**Add to design:**
- [ ] Add Activity Feed and Communication/Comment tab 
- [ ] change ‘CFO’ to Finance Director 
- [ ] Remove "checked"
- [ ] Dev needs to know where information is coming from
- [ ] fields in form is ‘easy’ to move around
- [ ] update status is a pop up (in the Action to take box)
- [ ] no pdf version of the PAF is needed
- [ ] could add more user roles under GC, CEO, etc. (more people to the bureaucracy)

**Misc.**
- [ ] [Activity Feed i](https://github.com/OpenTechFund/apply-app/issues/11) is a history or system of record of 'approvals' - what do auditors need to know? 
- [ ] Users need ‘Approver’ + Finance or Contracting user roles to approve PAF


**Next Steps:**
OTF needs to provide feedback on the content and order of information. What is the most important info? Is all the info there?
