### ISSUE TITLE
GC, CFO, CEO can request changes to PAF

### ISSUE THREAD

**Issue by ei8fdb** [OpenTechFund/apply-app#7]
(This issue is a work-in-progress, so I'm locking it until I've finished documenting it fully. If you want to edit it, let me know.) 

## Additional context
This is a sub-issue of the meta #2 

At the moment, we think the process for the GC, CFO, CEO approval will be the same. For now, the same ticket will be used for these 3 users. Collectively I will refer to them as "PAF Approver".

## User story

> As PAF Approver, I want to request changes to a submitted Project Approval Form so that I can review the correct information.

---

## To-Do
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [ ] Di to help organise testing/feedback session with OTF users
- [ ] do testing/feedback session with OTF users
- [ ] OTF to sign-off
- [ ] @OpenTechFund/design make sure final designs are attached to issue

**Comment by Erioldoesdesign** [comment]
@Di to set up a meeting with OTF re. approval process and what it looks like with Bernard.

**Comment by di** [comment]
Hi, I think you meant to mention someone else!

**Comment by Erioldoesdesign** [comment]
> Hi, I think you meant to mention someone else!

I certainly did! apologies!

**Comment by ei8fdb** [comment]
@Erioldoesdesign you mean @fourthletter

**Comment by Erioldoesdesign** [comment]
It's because I copy pasted from our miro board 🤦
